#pragma once

#include "Common.hpp"

struct BoundingBox {
  Vector3 min;
  Vector3 max;
};

enum class ItemType {
  BLOCK_SOLID,
  BLOCK_TRANSPARENT,
  BLOCK_FLUID,
  BLOCK_UI,
  BLOCK_FUNCTIONAL,
  TOOL_SHOVEL,
  TOOL_PICKAXE,
  TOOL_AXE,
  TOOL_WEAPON,
  ARMOR_HELMET,
  ARMOR_CHESTPLATE,
  ARMOR_LEGGINGS,
  ARMOR_BOOTS,
  ITEM_GENERAL
};

enum class BlockIDDef {
  Air,
  Grass,
  Dirt,
  Stone,
  Bedrock,
  Water,
  Wood,
  Leaves,
  Sand,
  Glowstone,
  DiamondOre,
  CoalOre,
  RedstoneOre,
  IronOre,
  LapisLazuliOre,
  GoldOre,
  EmeraldOre,
  CopperOre,
  AncientDebris,
  Cobblestone,
  Gravel,
  Ice,
  Snow,
  Planks,
  CraftingTable,
  Furnace,
  Chest,
  AmethystShard,
  Arrow,
  BlazePowder,
  BlazeRod,
  AmethystBlock,
  CoalBlock,
  CopperBlock,
  DiamondBlock,
  EmeraldBlock,
  GoldBlock,
  IronBlock,
  LapisBlock,
  NetheriteBlock,
  QuartzBlock,
  RawCopperBlock,
  RawGoldBlock,
  RawIronBlock,
  RedstoneBlock,
  Bone,
  Book,
  Bow,
  Brush,
  CarrotOnStick,
  ChainmailBoots,
  ChainmailChestplate,
  ChainmailHelmet,
  ChainmailLeggings,
  Charcoal,
  Clay,
  Coal,
  CookedChicken,
  CookedMutton,
  CookedPorkchop,
  DeepslateCoalOre,
  DeepslateCopperOre,
  DeepslateDiamondOre,
  DeepslateEmeraldOre,
  DeepslateGoldOre,
  DeepslateIronOre,
  DeepslateLapisOre,
  DeepslateRedstoneOre,
  DiamondAxe,
  DiamondBoots,
  DiamondChestplate,
  DiamondHelmet,
  DiamondHoe,
  DiamondHorseArmor,
  DiamondIngot,
  DiamondLeggings,
  DiamondShovel,
  DiamondSword,
  Emerald,
  EnderPearl,
  Feather,
  Firework,
  FishingRod,
  Flint,
  FlintAndSteel,
  GlowPowder,
  GoldIngot,
  GoldNugget,
  GoldenAxe,
  GoldenBoots,
  GoldenChestplate,
  GoldenHelmet,
  GoldenHoe,
  GoldenHorseArmor,
  GoldenLeggings,
  GoldenPickaxe,
  GoldenShovel,
  GoldenSword,
  Gunpowder,
  IronAxe,
  IronBoots,
  IronChestplate,
  IronHelmet,
  IronHoe,
  IronHorseArmor,
  IronIngot,
  IronLeggings,
  IronNugget,
  IronPickaxe,
  IronShovel,
  IronSword,
  KnowledgeBook,
  LapisLazuli,
  LeatherBoots,
  LeatherHelmet,
  LeatherHorseArmor,
  Leather,
  LeatherLeggings,
  LeatherChestplate,
  NetherGoldOre,
  Quartz,
  NetherQuartzOre,
  WitherStar,
  NetheriteAxe,
  NetheriteBoots,
  NetheriteChestplate,
  NetheriteHelmet,
  NetheriteHoe,
  NetheriteIngot,
  NetheriteLeggings,
  NetheritePickaxe,
  NetheriteScrap,
  NetheriteShovel,
  NetheriteSword,
  Paper,
  RawBeef,
  RawChicken,
  RawCopper,
  RawGold,
  RawIron,
  RawMutton,
  RawPorkchop,
  SandStone,
  Shears,
  ShulkerShell,
  CookedBeef,
  Stick,
  StoneAxe,
  StoneBricks,
  StoneHoe,
  StonePickaxe,
  StoneShovel,
  StoneSword,
  Sugar,
  Trident,
  TurtleHelmet,
  FishingPoleWithFungus,
  Hay,
  WoodenAxe,
  WoodenHoe,
  WoodenPickaxe,
  WoodenShovel,
  WoodenSword,
};

struct Block {
  char Name[32];
  short Textures[6]; // Front, Back, Right, Left, Top, Bottom
  short Luminance;
  short Drop;
  ItemType Type;
  bool isSolid;
  bool isFullBlock;
  bool canPlace;
  float BreakTime;
  BoundingBox *collisionBoxes;
  std::pair<int, int> *Storage;

  bool hasUI() const { return Type == ItemType::BLOCK_UI; }
  bool isFunctional() const { return Type == ItemType::BLOCK_FUNCTIONAL; }
  bool isTransparent() const {
    return Type == ItemType::BLOCK_TRANSPARENT || Type == ItemType::BLOCK_FLUID;
  }
  bool isWater() const { return Type == ItemType::BLOCK_FLUID; }
};
#define ALL(x) {x,x,x,x,x,x}

constexpr Block BlockDefinitions[] = {
    {"Air", {0}, 0, 0, ItemType::BLOCK_TRANSPARENT, false, false, false, 0.0f, nullptr, nullptr},
    {"Grass",{1, 1, 1, 1, 0, 2},0,(short)BlockIDDef::Dirt,ItemType::BLOCK_SOLID,true,true,true,0.6f,nullptr,nullptr},
    {"Dirt",ALL(2),0,(short)BlockIDDef::Dirt,ItemType::BLOCK_SOLID,true,true,true,0.5f,nullptr,nullptr},
    {"Stone",ALL(3),0,(short)BlockIDDef::Cobblestone,ItemType::BLOCK_SOLID,true,true,true,1.5f,nullptr,nullptr},
    {"Bedrock", ALL(4), 0, (short)BlockIDDef::Air, ItemType::BLOCK_SOLID, true, true, false, -1.0f, nullptr, nullptr},
    {"Water", ALL(5), 0, (short)BlockIDDef::Air, ItemType::BLOCK_FLUID, false, false, false, 0.0f, nullptr, nullptr},
    {"Wood", {6, 6, 6, 6, 10, 10}, 0, (short)BlockIDDef::Wood, ItemType::BLOCK_SOLID, true, true, true, 2.0f, nullptr, nullptr},
    {"Leaves", ALL(7), 0, (short)BlockIDDef::Air, ItemType::BLOCK_SOLID, true, false, true, 0.2f, nullptr, nullptr},
    {"Sand", ALL(8), 0, (short)BlockIDDef::Sand, ItemType::BLOCK_SOLID, true, true, true, 0.5f, nullptr, nullptr},
    {"Glowstone", ALL(9), 15, (short)BlockIDDef::Glowstone, ItemType::BLOCK_SOLID, true, true, true, 0.3f, nullptr, nullptr},
    {"Diamond Ore", ALL(11), 0, (short)BlockIDDef::DiamondIngot, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Coal Ore", ALL(12), 0, (short)BlockIDDef::Coal, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Redstone Ore", ALL(13), 0, (short)BlockIDDef::RedstoneOre, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Iron Ore", ALL(14), 0, (short)BlockIDDef::IronIngot, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Lapis Lazuli Ore", ALL(15), 0, (short)BlockIDDef::LapisLazuli, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Gold Ore", ALL(16), 0, (short)BlockIDDef::RawGold, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Emerald Ore", ALL(17), 0, (short)BlockIDDef::Emerald, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Copper Ore", ALL(18), 0, (short)BlockIDDef::RawCopper, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Ancient Debris", {20, 20, 20, 20, 19, 19}, 0, (short)BlockIDDef::AncientDebris, ItemType::BLOCK_SOLID, true, true, true, 30.0f, nullptr, nullptr},
    {"Cobblestone", ALL(21), 0, (short)BlockIDDef::Cobblestone, ItemType::BLOCK_SOLID, true, true, true, 2.0f, nullptr, nullptr},
    {"Gravel", ALL(22), 0, (short)BlockIDDef::Gravel, ItemType::BLOCK_SOLID, true, true, true, 0.6f, nullptr, nullptr},
    {"Ice", ALL(23), 0, (short)BlockIDDef::Ice, ItemType::BLOCK_SOLID, true, true, true, 0.5f, nullptr, nullptr},
    {"Snow", ALL(24), 0, (short)BlockIDDef::Snow, ItemType::BLOCK_SOLID, true, true, true, 0.1f, nullptr, nullptr},
    {"Planks", ALL(25), 0, (short)BlockIDDef::Planks, ItemType::BLOCK_SOLID, true, true, true, 2.0f, nullptr, nullptr},
    {"Crafting Table", {28, 28, 27, 27, 26, 25}, 0, (short)BlockIDDef::CraftingTable, ItemType::BLOCK_UI, true, true, true, 2.5f, nullptr, nullptr},
    {"Furnace", {30, 32, 32, 32, 31, 31}, 0, (short)BlockIDDef::Furnace, ItemType::BLOCK_UI, true, true, true, 3.5f, nullptr, nullptr},
    {"Chest", {34, 35, 35, 35, 33, 33}, 0, (short)BlockIDDef::Chest, ItemType::BLOCK_UI, true, true, true, 2.5f, nullptr, nullptr},
    {"Amethyst Shard", {36}, 0, (short)BlockIDDef::AmethystShard, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Arrow", {37}, 0, (short)BlockIDDef::Arrow, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Blaze Powder", {38}, 0, (short)BlockIDDef::BlazePowder, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Blaze Rod", {39}, 0, (short)BlockIDDef::BlazeRod, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Amethyst Block", ALL(40), 0, (short)BlockIDDef::AmethystBlock, ItemType::BLOCK_SOLID, true, true, true, 1.5f, nullptr, nullptr},
    {"Coal Block", ALL(41), 0, (short)BlockIDDef::CoalBlock, ItemType::BLOCK_SOLID, true, true, true, 5.0f, nullptr, nullptr},
    {"Copper Block", ALL(42), 0, (short)BlockIDDef::CopperBlock, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Diamond Block", ALL(43), 0, (short)BlockIDDef::DiamondBlock, ItemType::BLOCK_SOLID, true, true, true, 5.0f, nullptr, nullptr},
    {"Emerald Block", ALL(44), 0, (short)BlockIDDef::EmeraldBlock, ItemType::BLOCK_SOLID, true, true, true, 5.0f, nullptr, nullptr},
    {"Gold Block", ALL(45), 0, (short)BlockIDDef::GoldBlock, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Iron Block", ALL(46), 0, (short)BlockIDDef::IronBlock, ItemType::BLOCK_SOLID, true, true, true, 5.0f, nullptr, nullptr},
    {"Lapis Block", ALL(47), 0, (short)BlockIDDef::LapisBlock, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Netherite Block", ALL(48), 0, (short)BlockIDDef::NetheriteBlock, ItemType::BLOCK_SOLID, true, true, true, 50.0f, nullptr, nullptr},
    {"Quartz Block", ALL(49), 0, (short)BlockIDDef::QuartzBlock, ItemType::BLOCK_SOLID, true, true, true, 0.8f, nullptr, nullptr},
    {"Raw Copper Block", ALL(50), 0, (short)BlockIDDef::RawCopperBlock, ItemType::BLOCK_SOLID, true, true, true, 5.0f, nullptr, nullptr},
    {"Raw Gold Block", ALL(51), 0, (short)BlockIDDef::RawGoldBlock, ItemType::BLOCK_SOLID, true, true, true, 5.0f, nullptr, nullptr},
    {"Raw Iron Block", ALL(52), 0, (short)BlockIDDef::RawIronBlock, ItemType::BLOCK_SOLID, true, true, true, 5.0f, nullptr, nullptr},
    {"Redstone Block", ALL(53), 0, (short)BlockIDDef::RedstoneBlock, ItemType::BLOCK_SOLID, true, true, true, 5.0f, nullptr, nullptr},
    {"Bone", {54}, 0, (short)BlockIDDef::Bone, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Book", {55}, 0, (short)BlockIDDef::Book, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Bow", {59}, 0, (short)BlockIDDef::Bow, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Brush", {60}, 0, (short)BlockIDDef::Brush, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Carrot on a Stick", {61}, 0, (short)BlockIDDef::CarrotOnStick, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Chainmail Boots", {63}, 0, 0, ItemType::ARMOR_CHESTPLATE, false, false, false, 0.0f, nullptr, nullptr},
    {"Chainmail Chestplate", {64}, 0, 0, ItemType::ARMOR_CHESTPLATE, false, false, false, 0.0f, nullptr, nullptr},
    {"Chainmail Helmet", {65}, 0, 0, ItemType::ARMOR_HELMET, false, false, false, 0.0f, nullptr, nullptr},
    {"Chainmail Leggings", {66}, 0, 0, ItemType::ARMOR_LEGGINGS, false, false, false, 0.0f, nullptr, nullptr},
    {"Charcoal", {67}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Clay", {68}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Coal", {69}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Cooked Chicken", {70}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Cooked Mutton", {71}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Cooked Porkchop", {72}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Deepslate Coal Ore", ALL(73), 0, (short)BlockIDDef::DeepslateCoalOre, ItemType::BLOCK_SOLID, true, true, true, 4.5f, nullptr, nullptr},
    {"Deepslate Copper Ore", ALL(74), 0, (short)BlockIDDef::DeepslateCopperOre, ItemType::BLOCK_SOLID, true, true, true, 4.5f, nullptr, nullptr},
    {"Deepslate Diamond Ore", ALL(75), 0, (short)BlockIDDef::DeepslateDiamondOre, ItemType::BLOCK_SOLID, true, true, true, 4.5f, nullptr, nullptr},
    {"Deepslate Emerald Ore", ALL(76), 0, (short)BlockIDDef::DeepslateEmeraldOre, ItemType::BLOCK_SOLID, true, true, true, 4.5f, nullptr, nullptr},
    {"Deepslate Gold Ore", ALL(77), 0, (short)BlockIDDef::DeepslateGoldOre, ItemType::BLOCK_SOLID, true, true, true, 4.5f, nullptr, nullptr},
    {"Deepslate Iron Ore", ALL(78), 0, (short)BlockIDDef::DeepslateIronOre, ItemType::BLOCK_SOLID, true, true, true, 4.5f, nullptr, nullptr},
    {"Deepslate Lapis Ore", ALL(79), 0, (short)BlockIDDef::DeepslateLapisOre, ItemType::BLOCK_SOLID, true, true, true, 4.5f, nullptr, nullptr},
    {"Deepslate Redstone Ore", ALL(80), 0, 0, ItemType::BLOCK_SOLID, true, true, true, 4.5f, nullptr, nullptr},
    {"Diamond Axe", {81}, 0, 0, ItemType::TOOL_AXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Diamond Boots", {82}, 0, 0, ItemType::ARMOR_BOOTS, false, false, false, 0.0f, nullptr, nullptr},
    {"Diamond Chestplate", {83}, 0, 0, ItemType::ARMOR_CHESTPLATE, false, false, false, 0.0f, nullptr, nullptr},
    {"Diamond Helmet", {84}, 0, 0, ItemType::ARMOR_HELMET, false, false, false, 0.0f, nullptr, nullptr},
    {"Diamond Hoe", {85}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Diamond Horse Armor", {86}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Diamond Ingot", {87}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Diamond Leggings", {88}, 0, 0, ItemType::ARMOR_LEGGINGS, false, false, false, 0.0f, nullptr, nullptr},
    {"Diamond Shovel", {89}, 0, 0, ItemType::TOOL_SHOVEL, false, false, false, 0.0f, nullptr, nullptr},
    {"Diamond Sword", {90}, 0, 0, ItemType::TOOL_WEAPON, false, false, false, 0.0f, nullptr, nullptr},
    {"Emerald", {91}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Ender Pearl", {92}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Firework", {93}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Feather", {94}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Fishing Rod", {95}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Flint", {96}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Flint and Steel", {97}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Glow Powder", {98}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Gold Ingot", {99}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Gold Nugget", {100}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Golden Axe", {101}, 0, 0, ItemType::TOOL_AXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Golden Boots", {102}, 0, 0, ItemType::ARMOR_BOOTS, false, false, false, 0.0f, nullptr, nullptr},
    {"Golden Chestplate", {103}, 0, 0, ItemType::ARMOR_CHESTPLATE, false, false, false, 0.0f, nullptr, nullptr},
    {"Golden Helmet", {104}, 0, 0, ItemType::ARMOR_HELMET, false, false, false, 0.0f, nullptr, nullptr},
    {"Golden Hoe", {105}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Golden Horse Armor", {106}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Golden Leggings", {107}, 0, 0, ItemType::ARMOR_LEGGINGS, false, false, false, 0.0f, nullptr, nullptr},
    {"Golden Pickaxe", {108}, 0, 0, ItemType::TOOL_PICKAXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Golden Shovel", {109}, 0, 0, ItemType::TOOL_SHOVEL, false, false, false, 0.0f, nullptr, nullptr},
    {"Golden Sword", {110}, 0, 0, ItemType::TOOL_WEAPON, false, false, false, 0.0f, nullptr, nullptr},
    {"Gunpowder", {111}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Axe", {112}, 0, 0, ItemType::TOOL_AXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Boots", {113}, 0, 0, ItemType::TOOL_AXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Chestplate", {114}, 0, 0, ItemType::ARMOR_CHESTPLATE, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Helmet", {115}, 0, 0, ItemType::ARMOR_HELMET, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Hoe", {116}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Horse Armor", {117}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Ingot", {118}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Leggings", {119}, 0, 0, ItemType::ARMOR_LEGGINGS, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Nugget", {120}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Pickaxe", {121}, 0, 0, ItemType::TOOL_PICKAXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Shovel", {122}, 0, 0, ItemType::TOOL_SHOVEL, false, false, false, 0.0f, nullptr, nullptr},
    {"Iron Sword", {123}, 0, 0, ItemType::TOOL_WEAPON, false, false, false, 0.0f, nullptr, nullptr},
    {"Knowledge Book", {124}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Lapis Lazuli", {125}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Leather Boots", {126}, 0, 0, ItemType::ARMOR_BOOTS, false, false, false, 0.0f, nullptr, nullptr},
    {"Leather Helmet", {127}, 0, 0, ItemType::ARMOR_BOOTS, false, false, false, 0.0f, nullptr, nullptr},
    {"Leather Horse Armor", {128}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Leather", {129}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Leather Leggings", {130}, 0, 0, ItemType::ARMOR_LEGGINGS, false, false, false, 0.0f, nullptr, nullptr},
    {"Leather Chestplate", {131}, 0, 0, ItemType::ARMOR_CHESTPLATE, false, false, false, 0.0f, nullptr, nullptr},
    {"Nether Gold Ore", ALL(132), 0, (short)BlockIDDef::NetherGoldOre, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Quartz", {133}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Nether Quartz Ore", ALL(134), 0, (short)BlockIDDef::NetherQuartzOre, ItemType::BLOCK_SOLID, true, true, true, 3.0f, nullptr, nullptr},
    {"Wither Star", {135}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Netherite Axe", {136}, 0, 0, ItemType::TOOL_AXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Netherite Boots", {137}, 0, 0, ItemType::ARMOR_BOOTS, false, false, false, 0.0f, nullptr, nullptr},
    {"Netherite Chestplate", {138}, 0, 0, ItemType::ARMOR_CHESTPLATE, false, false, false, 0.0f, nullptr, nullptr},
    {"Netherite Helmet", {139}, 0, 0, ItemType::ARMOR_HELMET, false, false, false, 0.0f, nullptr, nullptr},
    {"Netherite Hoe", {140}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Netherite Ingot", {141}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Netherite Leggings", {142}, 0, 0, ItemType::ARMOR_LEGGINGS, false, false, false, 0.0f, nullptr, nullptr},
    {"Netherite Pickaxe", {143}, 0, 0, ItemType::TOOL_PICKAXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Netherite Scrap", {144}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Netherite Shovel", {145}, 0, 0, ItemType::TOOL_SHOVEL, false, false, false, 0.0f, nullptr, nullptr},
    {"Netherite Sword", {146}, 0, 0, ItemType::TOOL_WEAPON, false, false, false, 0.0f, nullptr, nullptr},
    {"Paper", {147}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Raw Beef", {148}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Raw Chicken", {149}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Raw Copper", {150}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Raw Gold", {151}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Raw Iron", {152}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Raw Mutton", {153}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Raw Porkchop", {154}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"SandStone", {156, 156, 156, 156, 157, 155}, 0, 0, ItemType::BLOCK_SOLID, false, false, false, 3.0f, nullptr, nullptr},
    {"Shears", {158}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Shulker Shell", {159}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Cooked Beef", {160}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Stick", {161}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Stone Axe", {162}, 0, 0, ItemType::TOOL_AXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Stone Bricks", ALL(163), 0, (short)BlockIDDef::StoneBricks, ItemType::BLOCK_SOLID, true, true, true, 1.5f, nullptr, nullptr},
    {"Stone Hoe", {164}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Stone Pickaxe", {165}, 0, 0, ItemType::TOOL_PICKAXE, false, false, false,0.0f,nullptr,nullptr},
    {"Stone Shovel",{166},0,0,ItemType::TOOL_SHOVEL,false,false,false,0.0f,nullptr,nullptr},
    {"Stone Sword",{167},0,0,ItemType::TOOL_WEAPON,false,false,false,0.0f,nullptr,nullptr},
    {"Sugar",{168},0,0,ItemType::ITEM_GENERAL,false,false,false,0.0f,nullptr,nullptr},
    {"Trident",{169},0,0,ItemType::TOOL_WEAPON,false,false,false,0.0f,nullptr,nullptr},
    {"Turtle Helmet",{170},0,0,ItemType::ARMOR_HELMET,false,false,false,0.0f,nullptr,nullptr},
    {"Fishing pole with fungus", {171}, 0, 0, ItemType::TOOL_AXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Hay", {172}, 0, 0, ItemType::ITEM_GENERAL, true, true, true, 0.5f, nullptr, nullptr},
    {"Wooden Axe", {173}, 0, 0, ItemType::TOOL_AXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Wooden Hoe", {174}, 0, 0, ItemType::ITEM_GENERAL, false, false, false, 0.0f, nullptr, nullptr},
    {"Wooden Pickaxe", {175}, 0, 0, ItemType::TOOL_PICKAXE, false, false, false, 0.0f, nullptr, nullptr},
    {"Wooden Shovel", {176}, 0, 0, ItemType::TOOL_SHOVEL, false, false, false, 0.0f, nullptr, nullptr},
    {"Wooden Sword", {177}, 0, 0, ItemType::TOOL_WEAPON, false, false, false, 0.0f, nullptr, nullptr},
};

constexpr unsigned int BlockDefinitionsAmount =
    sizeof(BlockDefinitions) / sizeof(BlockDefinitions[0]);
#define BlockDef BlockDefinitions
#define BlockNum BlockDefinitionsAmount