#pragma once

#include "Common.hpp"
#include <optional>
#include <vector>

struct BoundingBox {
  Vector3 min;
  Vector3 max;
};

enum class ItemType {
  BLOCK_SOLID,
  BLOCK_TRANSPARENT,
  BLOCK_FLUID,
  BLOCK_UI,
  BLOCK_FUNCTIONAL,
  TOOL_SHOVEL,
  TOOL_PICKAXE,
  TOOL_AXE,
  TOOL_WEAPON,
  ARMOR_HELMET,
  ARMOR_CHESTPLATE,
  ARMOR_LEGGINGS,
  ARMOR_BOOTS,
  ITEM_GENERAL,
  FUEL
};

enum class BlockIDDef {
  Air,
  Grass,
  Dirt,
  Stone,
  Bedrock,
  Water,
  Wood,
  Leaves,
  Sand,
  Glowstone,
  DiamondOre,
  CoalOre,
  RedstoneOre,
  IronOre,
  LapisLazuliOre,
  GoldOre,
  EmeraldOre,
  CopperOre,
  AncientDebris,
  Cobblestone,
  Gravel,
  Ice,
  Snow,
  Planks,
  CraftingTable,
  Furnace,
  Chest,
  AmethystShard,
  Arrow,
  BlazePowder,
  BlazeRod,
  AmethystBlock,
  CoalBlock,
  CopperBlock,
  DiamondBlock,
  EmeraldBlock,
  GoldBlock,
  IronBlock,
  LapisBlock,
  NetheriteBlock,
  QuartzBlock,
  RawCopperBlock,
  RawGoldBlock,
  RawIronBlock,
  RedstoneBlock,
  Bone,
  Book,
  Bow,
  Brush,
  CarrotOnStick,
  ChainmailBoots,
  ChainmailChestplate,
  ChainmailHelmet,
  ChainmailLeggings,
  Charcoal,
  Clay,
  Coal,
  CookedChicken,
  CookedMutton,
  CookedPorkchop,
  DeepslateCoalOre,
  DeepslateCopperOre,
  DeepslateDiamondOre,
  DeepslateEmeraldOre,
  DeepslateGoldOre,
  DeepslateIronOre,
  DeepslateLapisOre,
  DeepslateRedstoneOre,
  DiamondAxe,
  DiamondBoots,
  DiamondChestplate,
  DiamondHelmet,
  DiamondHoe,
  DiamondHorseArmor,
  DiamondIngot,
  DiamondLeggings,
  DiamondShovel,
  DiamondSword,
  Emerald,
  EnderPearl,
  Feather,
  Firework,
  FishingRod,
  Flint,
  FlintAndSteel,
  GlowPowder,
  GoldIngot,
  GoldNugget,
  GoldenAxe,
  GoldenBoots,
  GoldenChestplate,
  GoldenHelmet,
  GoldenHoe,
  GoldenHorseArmor,
  GoldenLeggings,
  GoldenPickaxe,
  GoldenShovel,
  GoldenSword,
  Gunpowder,
  IronAxe,
  IronBoots,
  IronChestplate,
  IronHelmet,
  IronHoe,
  IronHorseArmor,
  IronIngot,
  IronLeggings,
  IronNugget,
  IronPickaxe,
  IronShovel,
  IronSword,
  KnowledgeBook,
  LapisLazuli,
  LeatherBoots,
  LeatherHelmet,
  LeatherHorseArmor,
  Leather,
  LeatherLeggings,
  LeatherChestplate,
  NetherGoldOre,
  Quartz,
  NetherQuartzOre,
  WitherStar,
  NetheriteAxe,
  NetheriteBoots,
  NetheriteChestplate,
  NetheriteHelmet,
  NetheriteHoe,
  NetheriteIngot,
  NetheriteLeggings,
  NetheritePickaxe,
  NetheriteScrap,
  NetheriteShovel,
  NetheriteSword,
  Paper,
  RawBeef,
  RawChicken,
  RawCopper,
  RawGold,
  RawIron,
  RawMutton,
  RawPorkchop,
  SandStone,
  Shears,
  ShulkerShell,
  CookedBeef,
  Stick,
  StoneAxe,
  StoneBricks,
  StoneHoe,
  StonePickaxe,
  StoneShovel,
  StoneSword,
  Sugar,
  Trident,
  TurtleHelmet,
  FishingPoleWithFungus,
  Hay,
  WoodenAxe,
  WoodenHoe,
  WoodenPickaxe,
  WoodenShovel,
  WoodenSword,
};

struct Block {
  char Name[32];
  short Textures[6]; // Front, Back, Right, Left, Top, Bottom
  short Luminance;
  short Drop;
  ItemType Type;
  std::optional<float> BreakTime;
  std::optional<std::vector<BoundingBox>> collisionBoxes;
  std::optional<std::vector<std::pair<int, int>>> Storage;

  bool hasUI() const { return Type == ItemType::BLOCK_UI; }
  bool isFunctional() const { return Type == ItemType::BLOCK_FUNCTIONAL; }
  bool isTransparent() const {
 return Type == ItemType::BLOCK_TRANSPARENT || Type == ItemType::BLOCK_FLUID;
  }
  bool isWater() const { return Type == ItemType::BLOCK_FLUID; }
  bool CanPlace() const { return Type == ItemType::BLOCK_FLUID || Type == ItemType::BLOCK_FUNCTIONAL || Type == ItemType::BLOCK_SOLID || Type == ItemType::BLOCK_TRANSPARENT|| Type == ItemType::BLOCK_UI;};
  bool IsSolid() const {return CanPlace() && Type != ItemType::BLOCK_FLUID;};
};
#define ALL(x) {x,x,x,x,x,x}

const Block BlockDefinitions[] = {
  {"Air", {0}, 0, 0, ItemType::BLOCK_TRANSPARENT },
  {"Grass",{1, 1, 1, 1, 0, 2},0,(short)BlockIDDef::Dirt, ItemType::BLOCK_SOLID},
  {"Dirt",ALL(2),0,(short)BlockIDDef::Dirt,ItemType::BLOCK_SOLID, 0.5f},
  {"Stone",ALL(3),0,(short)BlockIDDef::Cobblestone,ItemType::BLOCK_SOLID, 1.5f},
  {"Bedrock", ALL(4), 0, (short)BlockIDDef::Air, ItemType::BLOCK_SOLID, -1.0f },
  {"Water", ALL(5), 0, (short)BlockIDDef::Air, ItemType::BLOCK_FLUID},
  {"Wood", {6, 6, 6, 6, 10, 10}, 0, (short)BlockIDDef::Wood, ItemType::BLOCK_SOLID, 2.0f },
  {"Leaves", ALL(7), 0, (short)BlockIDDef::Air, ItemType::BLOCK_SOLID, 0.2f },
  {"Sand", ALL(8), 0, (short)BlockIDDef::Sand, ItemType::BLOCK_SOLID, 0.5f },
  {"Glowstone", ALL(9), 15, (short)BlockIDDef::Glowstone, ItemType::BLOCK_SOLID, 0.3f },
  {"Diamond Ore", ALL(11), 0, (short)BlockIDDef::DiamondIngot, ItemType::BLOCK_SOLID, 3.0f },
  {"Coal Ore", ALL(12), 0, (short)BlockIDDef::Coal, ItemType::BLOCK_SOLID, 3.0f },
  {"Redstone Ore", ALL(13), 0, (short)BlockIDDef::RedstoneOre, ItemType::BLOCK_SOLID, 3.0f },
  {"Iron Ore", ALL(14), 0, (short)BlockIDDef::RawIron, ItemType::BLOCK_SOLID, 3.0f },
  {"Lapis Lazuli Ore", ALL(15), 0, (short)BlockIDDef::LapisLazuli, ItemType::BLOCK_SOLID, 3.0f },
  {"Gold Ore", ALL(16), 0, (short)BlockIDDef::RawGold, ItemType::BLOCK_SOLID, 3.0f },
  {"Emerald Ore", ALL(17), 0, (short)BlockIDDef::Emerald, ItemType::BLOCK_SOLID, 3.0f },
  {"Copper Ore", ALL(18), 0, (short)BlockIDDef::RawCopper, ItemType::BLOCK_SOLID, 3.0f },
  {"Ancient Debris", {20, 20, 20, 20, 19, 19}, 0, (short)BlockIDDef::AncientDebris, ItemType::BLOCK_SOLID, 30.0f },
  {"Cobblestone", ALL(21), 0, (short)BlockIDDef::Cobblestone, ItemType::BLOCK_SOLID, 2.0f },
  {"Gravel", ALL(22), 0, (short)BlockIDDef::Gravel, ItemType::BLOCK_SOLID, 0.6f },
  {"Ice", ALL(23), 0, (short)BlockIDDef::Ice, ItemType::BLOCK_SOLID, 0.5f },
  {"Snow", ALL(24), 0, (short)BlockIDDef::Snow, ItemType::BLOCK_SOLID, 0.1f },
  {"Planks", ALL(25), 0, (short)BlockIDDef::Planks, ItemType::BLOCK_SOLID, 2.0f },
  {"Crafting Table", {28, 28, 27, 27, 26, 25}, 0, (short)BlockIDDef::CraftingTable, ItemType::BLOCK_UI, 2.5f },
  {"Furnace", {30, 32, 32, 32, 31, 31}, 0, (short)BlockIDDef::Furnace, ItemType::BLOCK_UI, 3.5f },
  {"Chest", {34, 35, 35, 35, 33, 33}, 0, (short)BlockIDDef::Chest, ItemType::BLOCK_UI, 2.5f },
  {"Amethyst Shard", {36}, 0, (short)BlockIDDef::AmethystShard, ItemType::ITEM_GENERAL },
  {"Arrow", {37}, 0, (short)BlockIDDef::Arrow, ItemType::ITEM_GENERAL },
  {"Blaze Powder", {38}, 0, (short)BlockIDDef::BlazePowder, ItemType::ITEM_GENERAL },
  {"Blaze Rod", {39}, 0, (short)BlockIDDef::BlazeRod, ItemType::ITEM_GENERAL },
  {"Amethyst Block", ALL(40), 0, (short)BlockIDDef::AmethystBlock, ItemType::BLOCK_SOLID, 1.5f },
  {"Coal Block", ALL(41), 0, (short)BlockIDDef::CoalBlock, ItemType::BLOCK_SOLID, 5.0f },
  {"Copper Block", ALL(42), 0, (short)BlockIDDef::CopperBlock, ItemType::BLOCK_SOLID, 3.0f },
  {"Diamond Block", ALL(43), 0, (short)BlockIDDef::DiamondBlock, ItemType::BLOCK_SOLID, 5.0f },
  {"Emerald Block", ALL(44), 0, (short)BlockIDDef::EmeraldBlock, ItemType::BLOCK_SOLID, 5.0f },
  {"Gold Block", ALL(45), 0, (short)BlockIDDef::GoldBlock, ItemType::BLOCK_SOLID, 3.0f },
  {"Iron Block", ALL(46), 0, (short)BlockIDDef::IronBlock, ItemType::BLOCK_SOLID, 5.0f },
  {"Lapis Block", ALL(47), 0, (short)BlockIDDef::LapisBlock, ItemType::BLOCK_SOLID, 3.0f },
  {"Netherite Block", ALL(48), 0, (short)BlockIDDef::NetheriteBlock, ItemType::BLOCK_SOLID, 50.0f },
  {"Quartz Block", ALL(49), 0, (short)BlockIDDef::QuartzBlock, ItemType::BLOCK_SOLID, 0.8f },
  {"Raw Copper Block", ALL(50), 0, (short)BlockIDDef::RawCopperBlock, ItemType::BLOCK_SOLID, 5.0f },
  {"Raw Gold Block", ALL(51), 0, (short)BlockIDDef::RawGoldBlock, ItemType::BLOCK_SOLID, 5.0f },
  {"Raw Iron Block", ALL(52), 0, (short)BlockIDDef::RawIronBlock, ItemType::BLOCK_SOLID, 5.0f },
  {"Redstone Block", ALL(53), 0, (short)BlockIDDef::RedstoneBlock, ItemType::BLOCK_SOLID, 5.0f },
  {"Bone", {54}, 0, (short)BlockIDDef::Bone, ItemType::ITEM_GENERAL },
  {"Book", {55}, 0, (short)BlockIDDef::Book, ItemType::ITEM_GENERAL },
  {"Bow", {59}, 0, (short)BlockIDDef::Bow, ItemType::ITEM_GENERAL },
  {"Brush", {60}, 0, (short)BlockIDDef::Brush, ItemType::ITEM_GENERAL },
  {"Carrot on a Stick", {61}, 0, (short)BlockIDDef::CarrotOnStick, ItemType::ITEM_GENERAL },
  {"Chainmail Boots", {63}, 0, 0, ItemType::ARMOR_CHESTPLATE },
  {"Chainmail Chestplate", {64}, 0, 0, ItemType::ARMOR_CHESTPLATE },
  {"Chainmail Helmet", {65}, 0, 0, ItemType::ARMOR_HELMET },
  {"Chainmail Leggings", {66}, 0, 0, ItemType::ARMOR_LEGGINGS },
  {"Charcoal", {67}, 0, 0, ItemType::FUEL },
  {"Clay", {68}, 0, 0, ItemType::ITEM_GENERAL },
  {"Coal", {69}, 0, 0, ItemType::FUEL },
  {"Cooked Chicken", {70}, 0, 0, ItemType::ITEM_GENERAL },
  {"Cooked Mutton", {71}, 0, 0, ItemType::ITEM_GENERAL },
  {"Cooked Porkchop", {72}, 0, 0, ItemType::ITEM_GENERAL },
  {"Deepslate Coal Ore", ALL(73), 0, (short)BlockIDDef::Coal, ItemType::BLOCK_SOLID, 4.5f },
  {"Deepslate Copper Ore", ALL(74), 0, (short)BlockIDDef::RawCopper, ItemType::BLOCK_SOLID, 4.5f },
  {"Deepslate Diamond Ore", ALL(75), 0, (short)BlockIDDef::DiamondIngot, ItemType::BLOCK_SOLID, 4.5f },
  {"Deepslate Emerald Ore", ALL(76), 0, (short)BlockIDDef::Emerald, ItemType::BLOCK_SOLID, 4.5f },
  {"Deepslate Gold Ore", ALL(77), 0, (short)BlockIDDef::RawGold, ItemType::BLOCK_SOLID, 4.5f },
  {"Deepslate Iron Ore", ALL(78), 0, (short)BlockIDDef::RawIron, ItemType::BLOCK_SOLID, 4.5f },
  {"Deepslate Lapis Ore", ALL(79), 0, (short)BlockIDDef::DeepslateLapisOre, ItemType::BLOCK_SOLID, 4.5f },
  {"Deepslate Redstone Ore", ALL(80), 0, 0, ItemType::BLOCK_SOLID, 4.5f },
  {"Diamond Axe", {81}, 0, 0, ItemType::TOOL_AXE },
  {"Diamond Boots", {82}, 0, 0, ItemType::ARMOR_BOOTS },
  {"Diamond Chestplate", {83}, 0, 0, ItemType::ARMOR_CHESTPLATE },
  {"Diamond Helmet", {84}, 0, 0, ItemType::ARMOR_HELMET },
  {"Diamond Hoe", {85}, 0, 0, ItemType::ITEM_GENERAL },
  {"Diamond Horse Armor", {86}, 0, 0, ItemType::ITEM_GENERAL },
  {"Diamond Ingot", {87}, 0, 0, ItemType::ITEM_GENERAL },
  {"Diamond Leggings", {88}, 0, 0, ItemType::ARMOR_LEGGINGS },
  {"Diamond Shovel", {89}, 0, 0, ItemType::TOOL_SHOVEL },
  {"Diamond Sword", {90}, 0, 0, ItemType::TOOL_WEAPON },
  {"Emerald", {91}, 0, 0, ItemType::ITEM_GENERAL },
  {"Ender Pearl", {92}, 0, 0, ItemType::ITEM_GENERAL },
  {"Firework", {93}, 0, 0, ItemType::ITEM_GENERAL },
  {"Feather", {94}, 0, 0, ItemType::ITEM_GENERAL },
  {"Fishing Rod", {95}, 0, 0, ItemType::ITEM_GENERAL },
  {"Flint", {96}, 0, 0, ItemType::ITEM_GENERAL },
  {"Flint and Steel", {97}, 0, 0, ItemType::ITEM_GENERAL },
  {"Glow Powder", {98}, 0, 0, ItemType::ITEM_GENERAL },
  {"Gold Ingot", {99}, 0, 0, ItemType::ITEM_GENERAL },
  {"Gold Nugget", {100}, 0, 0, ItemType::ITEM_GENERAL },
  {"Golden Axe", {101}, 0, 0, ItemType::TOOL_AXE },
  {"Golden Boots", {102}, 0, 0, ItemType::ARMOR_BOOTS },
  {"Golden Chestplate", {103}, 0, 0, ItemType::ARMOR_CHESTPLATE },
  {"Golden Helmet", {104}, 0, 0, ItemType::ARMOR_HELMET },
  {"Golden Hoe", {105}, 0, 0, ItemType::ITEM_GENERAL },
  {"Golden Horse Armor", {106}, 0, 0, ItemType::ITEM_GENERAL },
  {"Golden Leggings", {107}, 0, 0, ItemType::ARMOR_LEGGINGS },
  {"Golden Pickaxe", {108}, 0, 0, ItemType::TOOL_PICKAXE },
  {"Golden Shovel", {109}, 0, 0, ItemType::TOOL_SHOVEL },
  {"Golden Sword", {110}, 0, 0, ItemType::TOOL_WEAPON },
  {"Gunpowder", {111}, 0, 0, ItemType::ITEM_GENERAL },
  {"Iron Axe", {112}, 0, 0, ItemType::TOOL_AXE },
  {"Iron Boots", {113}, 0, 0, ItemType::TOOL_AXE },
  {"Iron Chestplate", {114}, 0, 0, ItemType::ARMOR_CHESTPLATE },
  {"Iron Helmet", {115}, 0, 0, ItemType::ARMOR_HELMET },
  {"Iron Hoe", {116}, 0, 0, ItemType::ITEM_GENERAL },
  {"Iron Horse Armor", {117}, 0, 0, ItemType::ITEM_GENERAL },
  {"Iron Ingot", {118}, 0, 0, ItemType::ITEM_GENERAL },
  {"Iron Leggings", {119}, 0, 0, ItemType::ARMOR_LEGGINGS },
  {"Iron Nugget", {120}, 0, 0, ItemType::ITEM_GENERAL },
  {"Iron Pickaxe", {121}, 0, 0, ItemType::TOOL_PICKAXE },
  {"Iron Shovel", {122}, 0, 0, ItemType::TOOL_SHOVEL },
  {"Iron Sword", {123}, 0, 0, ItemType::TOOL_WEAPON },
  {"Knowledge Book", {124}, 0, 0, ItemType::ITEM_GENERAL },
  {"Lapis Lazuli", {125}, 0, 0, ItemType::ITEM_GENERAL },
  {"Leather Boots", {126}, 0, 0, ItemType::ARMOR_BOOTS },
  {"Leather Helmet", {127}, 0, 0, ItemType::ARMOR_BOOTS },
  {"Leather Horse Armor", {128}, 0, 0, ItemType::ITEM_GENERAL },
  {"Leather", {129}, 0, 0, ItemType::ITEM_GENERAL },
  {"Leather Leggings", {130}, 0, 0, ItemType::ARMOR_LEGGINGS },
  {"Leather Chestplate", {131}, 0, 0, ItemType::ARMOR_CHESTPLATE },
  {"Nether Gold Ore", ALL(132), 0, (short)BlockIDDef::NetherGoldOre, ItemType::BLOCK_SOLID, 3.0f },
  {"Quartz", {133}, 0, 0, ItemType::ITEM_GENERAL },
  {"Nether Quartz Ore", ALL(134), 0, (short)BlockIDDef::NetherQuartzOre, ItemType::BLOCK_SOLID, 3.0f },
  {"Wither Star", {135}, 0, 0, ItemType::ITEM_GENERAL },
  {"Netherite Axe", {136}, 0, 0, ItemType::TOOL_AXE },
  {"Netherite Boots", {137}, 0, 0, ItemType::ARMOR_BOOTS },
  {"Netherite Chestplate", {138}, 0, 0, ItemType::ARMOR_CHESTPLATE },
  {"Netherite Helmet", {139}, 0, 0, ItemType::ARMOR_HELMET },
  {"Netherite Hoe", {140}, 0, 0, ItemType::ITEM_GENERAL },
  {"Netherite Ingot", {141}, 0, 0, ItemType::ITEM_GENERAL },
  {"Netherite Leggings", {142}, 0, 0, ItemType::ARMOR_LEGGINGS },
  {"Netherite Pickaxe", {143}, 0, 0, ItemType::TOOL_PICKAXE },
  {"Netherite Scrap", {144}, 0, 0, ItemType::ITEM_GENERAL },
  {"Netherite Shovel", {145}, 0, 0, ItemType::TOOL_SHOVEL },
  {"Netherite Sword", {146}, 0, 0, ItemType::TOOL_WEAPON },
  {"Paper", {147}, 0, 0, ItemType::ITEM_GENERAL },
  {"Raw Beef", {148}, 0, 0, ItemType::ITEM_GENERAL },
  {"Raw Chicken", {149}, 0, 0, ItemType::ITEM_GENERAL },
  {"Raw Copper", {150}, 0, 0, ItemType::ITEM_GENERAL },
  {"Raw Gold", {151}, 0, 0, ItemType::ITEM_GENERAL },
  {"Raw Iron", {152}, 0, 0, ItemType::ITEM_GENERAL },
  {"Raw Mutton", {153}, 0, 0, ItemType::ITEM_GENERAL },
  {"Raw Porkchop", {154}, 0, 0, ItemType::ITEM_GENERAL },
  {"SandStone", {156, 156, 156, 156, 157, 155}, 0, 0, ItemType::BLOCK_SOLID, 3.0f },
  {"Shears", {158}, 0, 0, ItemType::ITEM_GENERAL },
  {"Shulker Shell", {159}, 0, 0, ItemType::ITEM_GENERAL },
  {"Cooked Beef", {160}, 0, 0, ItemType::ITEM_GENERAL },
  {"Stick", {161}, 0, 0, ItemType::ITEM_GENERAL},
  {"Stone Axe", {162}, 0, 0, ItemType::TOOL_AXE},
  {"Stone Bricks", ALL(163), 0, (short)BlockIDDef::StoneBricks, ItemType::BLOCK_SOLID, 1.5f},
  {"Stone Hoe", {164}, 0, 0, ItemType::ITEM_GENERAL},
  {"Stone Pickaxe", {165}, 0, 0, ItemType::TOOL_PICKAXE},
  {"Stone Shovel",{166},0,0,ItemType::TOOL_SHOVEL},
  {"Stone Sword",{167},0,0,ItemType::TOOL_WEAPON},
  {"Sugar",{168},0,0,ItemType::ITEM_GENERAL},
  {"Trident",{169},0,0,ItemType::TOOL_WEAPON},
  {"Turtle Helmet",{170},0,0,ItemType::ARMOR_HELMET},
  {"Fishing pole with fungus", {171}, 0, 0, ItemType::TOOL_AXE},
  {"Hay", {172}, 0, 0, ItemType::ITEM_GENERAL, 0.5f},
  {"Wooden Axe", {173}, 0, 0, ItemType::TOOL_AXE},
  {"Wooden Hoe", {174}, 0, 0, ItemType::ITEM_GENERAL},
  {"Wooden Pickaxe", {175}, 0, 0, ItemType::TOOL_PICKAXE},
  {"Wooden Shovel", {176}, 0, 0, ItemType::TOOL_SHOVEL},
  {"Wooden Sword", {177}, 0, 0, ItemType::TOOL_WEAPON},
};

constexpr unsigned int BlockDefinitionsAmount =
 sizeof(BlockDefinitions) / sizeof(BlockDefinitions[0]);
#define BlockDef BlockDefinitions
#define BlockNum BlockDefinitionsAmount